config/routes.rb
Rails.application.routes.draw do

  devise_for :users do
  get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root 'blogs#index'
  resources :users do
    member do
      resources :blogs do 
        get 'new_leave_type', on: :collection
        get 'deleting_leave_type', on: :member
      end
      resources :leave_availd_details do 
        post 'updating',on: :member
        get 'approval_leave',on: :member
        get 'reject_leave',on: :member
        get 'cancel_leave',on: :member
      end
    end
  end
     
    

end

app/models/employee_leave_balance.rb
class EmployeeLeaveBalance < ActiveRecord::Base
	belongs_to :user
	belongs_to :leave_type

	def self.create_leave_balance(user)
	  @leave_type = LeaveType.all
        @leave_type.each do |leave|
        employee_leave = EmployeeLeaveBalance.create(:user_id=>user,:leave_type_id=>leave.id,:status=>'Active',:total=>leave.total_leave,:leave_availd=>0,:balance=>leave.total_leave)
        end
	end

	def self.create_new_leave(leave)
	  @user = User.all
	   @user.each do |u|
	   employee_leave = EmployeeLeaveBalance.create(:user_id=>u.id,:leave_type_id=>leave.id,:status=>'Active',:total=>leave.total_leave,:leave_availd=>0,:balance=>leave.total_leave)
	   end
    end

    def self.approved_leave_balance(leave)
        emp_balance=self.find_by_user_id_and_leave_type_id(leave.user.id,leave.leave_type_id)
        balance=emp_balance.balance.to_i
        days = leave.no_of_days.to_i
        if balance > days
          new_balance = balance - days 
          emp_balance.update_attributes(balance: new_balance.to_i,leave_availd: days)
          status=true
        else 
        status=false
        end
        return status
    end
end

app/models/leave_availd_detail.rb
class LeaveAvaildDetail < ActiveRecord::Base
	belongs_to :user
	belongs_to :leave_type

	validates_presence_of :leave_type_id,{ message: "Please select Leave Type" }
	validates_presence_of :from_date
	validates_presence_of :to_date
	validates_presence_of :reasion
  after_create :apply_leave_of_mail

  def apply_leave_of_mail
    UserMailer.sending_mail(self).deliver_now
  end

	def self.create_user_leaves(user,from,to,leave,reasion)
		no_of_days = (to - from).to_i
    leave_balance = EmployeeLeaveBalance.find_by_leave_type_id_and_user_id(leave,user.id)
    if leave_balance.balance.to_i > no_of_days
        availd=self.new
        availd.user_id=user.id
        availd.leave_type_id =leave
        availd.from_date = from.strftime("%F")
        availd.to_date = to.strftime("%F")
        availd.no_of_days = no_of_days + 1
        availd.status = 'InProcess'
        availd.reasion = reasion
        status=availd.save!
    else
      status=false
    end
    return status
  end

    def self.update_leave(params,days)
      no_of_days = (params[:datepicker1].to_date - params[:datepicker].to_date).to_i
      leave= self.find_by_id(params[:id])
      leave.leave_type_id = params[:hobbies]
      leave.from_date = params[:datepicker]
      leave.to_date=params[:datepicker1]
      leave.no_of_days = days + 1
      leave.reasion = params[:reasion]
      leave.save!
    end

    def self.approve_leave(id)
      approve =self.find_by_id(id) 
      emp_leave_balance = EmployeeLeaveBalance.approved_leave_balance(approve)
      approve.update_attributes(status: 'Approved')

    end
end

app/models/leave_type.rb
class LeaveType < ActiveRecord::Base
	has_many :users
	has_many :employee_leave_balances, dependent: :destroy
	has_many :leave_availd_details, dependent: :destroy

	validates_uniqueness_of :name
	
	
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :employee_leave_balances
	has_many :leave_types, through: :employee_leave_balances
  has_many :leave_availd_details

	after_create :create_leave_balance
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    def create_leave_balance
    	EmployeeLeaveBalance.create_leave_balance(id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	before_action :configure_permitted_parameters, if: :devise_controller?

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
    def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:rolls,:name])
  end
  
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
	before_action :authenticate_user!
	layout 'blog'

  def index
    @user = current_user
    @emp_leave_balance = EmployeeLeaveBalance.where(:user_id=>@user.id)
    @leave_availd = LeaveAvaildDetail.where(:user_id=>@user.id,:status=>'InProcess')
  end
  
  def new
  	@leave_type=LeaveType.all
  end

  def new_leave_type
  	@leave_type = LeaveType.new
  end

  def create
    @leave_type = LeaveType.create(:name=>params[:name],:total_leave=>params[:total_leave],:status=>'Active')
    @emp_leave_balance = EmployeeLeaveBalance.create_new_leave(@leave_type)
    flash[:notice]="The Leave Type Was Successfully Create"
    redirect_to "/users/#{current_user.id}/blogs/new"
  end

  def deleting_leave_type
    @leave_type = LeaveType.find_by_id(params[:id])
    @leave_type.destroy
    redirect_to "/users/#{current_user.id}/blogs/new"
  end
  
end

app/controllers/leave_availd_details_controller.rb
class LeaveAvaildDetailsController < ApplicationController
	require 'date'
	layout 'blog'

  def index
    @leave_availd = LeaveAvaildDetail.where(:status=>'InProcess')
  end

	def new
		@leave_type =LeaveType.all
    end

    def create
      leave_type=params[:leave_type_id]
      from=params[:datepicker].to_date
      to=params[:datepicker1].to_date
      user = current_user
      reasion = params[:reasion]
      priveos = LeaveAvaildDetail.where('from_date >= (?) and to_date <= (?) and user_id =? and status!=?',from.strftime("%F"),to.strftime("%F"),user.id,'Approved')
       if priveos.blank?
       @leave_availd = LeaveAvaildDetail.create_user_leaves(user,from,to,leave_type,reasion)
        if @leave_availd
        flash[:notice]="The Leave Was Successfully Create"
        redirect_to '/'
        else
        flash[:notice]="The LeaveBalance Was Not is Not there"
        redirect_to '/'
        end
      else
        flash[:notice]="This Date Already Leave Applied"
        redirect_to '/'
      end
    end

    def edit
    	@leave_availd = LeaveAvaildDetail.where(:id=>params[:id])
    end

    def updating
     a=params[:datepicker].to_date
     b=params[:datepicker1].to_date
     c = (b - a).to_i
     @leave_update = LeaveAvaildDetail.update_leave(params,c)
     flash[:notice]="The Leave Was Successfully Updated"
     redirect_to "/"
    end

    def approval_leave
      leave = LeaveAvaildDetail.approve_leave(params[:id])
      if status ==true
        flash[:notice]="The Leave Was Successfully Approved"
        redirect_to "/"
      else
        flash[:notice]="The Leave Was Successfully Approved"
        redirect_to "/"
      end
    end

    def reject_leave
      leave =LeaveAvaildDetail.find(params[:id])
      if leave.present?
        leave.update_attribute("status","Rejected")
        flash[:notice]="The Leave Was Successfully Rejected"
        redirect_to "/"
      end
    end

    def cancel_leave
      leave =LeaveAvaildDetail.find(params[:id])
      if leave.present?
        UserMailer.cancel_leave(leave).deliver_now
        leave.destroy
        flash[:notice]="The Leave Was Successfully Canceld"
        redirect_to "/"
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/leave_availd_details_helper.rb
module LeaveAvaildDetailsHelper
end

app/views/blogs/index.html.erb
<div class="float-right"><%=link_to 'Apply Leavekk' ,new_leave_availd_detail_path(current_user),:class => 'navbar-link'%></div><br />
<div class="container">
  <h2>Leave Balance</h2>           
  <table class="table table-striped">
    <thead>
      
      <tr>
        <th>User Name</th>
        <th>Leave Type</th>
        <th>Total Leave</th>
        <th>Leave Availd</th>
        <th>Balance</th>
      </tr>
    </thead>
    <tbody>
    <%if @emp_leave_balance%>
    <%@emp_leave_balance.each do |balance|%>
      <tr>
        <td><%=balance.user.name%></td>
        <td><%=balance.leave_type.name%></td>
        <td><%=balance.total%></td>
        <td><%=balance.leave_availd%></td>
        <td><%=balance.balance%></td>
      </tr>
      <%end%><%end%>
    </tbody>
  </table>
  <br /><br />
  <h2>Applied Leaves</h2>
   <table class="table table-striped">
    <thead>
      <tr>
        <th>User Name</th>
        <th>Leave Type</th>
        <th>From</th>
        <th>To</th>
        <th>No Of Days</th>
        <th>Status</th>
        <th>Manager</th>
        <th>Reasion</th>
        <th></th>
      </tr>
      </thead>
      <%if @leave_availd%>
      <%@leave_availd.each do |availd|%>
      <tr>
        <td><%=availd.user.name%></td>
        <td><%=availd.leave_type.name%></td>
        <td><%=availd.from_date%></td>
        <td><%=availd.to_date%></td>
        <td><%=availd.no_of_days%></td>
        <td><%=availd.status%></td>
        <td><%=User.where('rolls=?',true).first.name%></td>
        <td><%=availd.reasion%></td>
        <td><%=link_to 'Edit',edit_leave_availd_detail_path(availd.id)%></td>
        <td><%=link_to 'Cancel',cancel_leave_leave_availd_detail_path(availd.id),:data => {:confirm => 'Are you sure?'}%></td>
        
      </tr>
      <%end%><%end%>
    </table>

</div>

app/views/blogs/new.html.erb
<%=link_to 'Create Leave Type',new_leave_type_blogs_path, :class => 'navbar-link'%>
<div class="container">
  <h2>Leave Types</h2>           
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Status</th>
        <th>Total Leave</th>
      </tr>
    </thead>
    <tbody>
    <%@leave_type.each do |leave|%>
      <tr>
        <td><%=leave.name%></td>
        <td><%=leave.status%></td>
        <td><%=leave.total_leave%></td>
        <td><%=link_to 'Delete',deleting_leave_type_blog_path(leave.id)%></td>
      </tr>
      <%end%>
    </tbody>
  </table>
</div>

app/views/blogs/new_leave_type.html.erb
  <%= form_tag(:controller => "blogs", :action => "create")%>
  <div class="container">           
  <table>
  	 <tr>
        <td style="width: 200px">Name</td>
        <td><%=text_field_tag :name%></td>
     </tr>
     <tr>
     	<td>Total Days</td>
     	<td><%=number_field_tag :total_leave,{min: 0, max: 30}%></td>
     </tr>
    </table>
   </div>
<%=submit_tag 'Create',:onclick=>'return check();'%>
<script>
  function check(){
    
    var name =document.getElementById("name").value;
    var days =document.getElementById("total_leave").value;
      if (name=="") {
        alert("please Enter LeaveTypeName")
        return false;
      }
      if (days=="") {
        alert("Please Enter Total Days")
        return false;
      } 
      if (days < 1) {
        alert('Select Postive Numbers')
        return false;
      }
  }
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Leave</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>	
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: "alert alert-info" %>
  <% end %>
<%= yield %>

</body>
</html>

app/views/layouts/blog.html.erb
<html>
<head>
<%= stylesheet_link_tag  'new.css', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>	
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/themes/base/jquery-ui.css" rel="stylesheet" />

      <script src = "https://code.jquery.com/jquery-1.10.2.js"></script>
      <script src = "https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
</head>
<body> 
   <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: "alert alert-info" %>
  <% end %>
	<div class="shadow"><b><center>Leave Management</center></b></div>
	   <div class="sidenav">
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <%= link_to 'Leave Type Create',new_blog_path(current_user), :class=>'navbar-link' if current_user.rolls==true%>
          <%= link_to 'Approve Leave Request',leave_availd_details_path(current_user),:class=>'navbar-link' if current_user.rolls ==true%>
        </div>
	    <div class="main">
        <%=yield%>
     	</div>
</body>
</html>

app/views/leave_availd_details/edit.html.erb
<%= form_tag updating_leave_availd_detail_path, :method => :post do %>
<table>
 	<tr>
 		<td style="width: 140px">Leave Type</td>
 		<td>
        <%#= select_tag :hobbies, options_for_select(LeaveType.all.collect { |e| [e.name,e.id]}),
          {:include_blank => LeaveType.where(id: @leave_availd.first.leave_type).collect{ |l| [l.name,l.id]}} %>
          <%=select_tag :hobbies,options_for_select(LeaveType.all.collect { |e| [e.name,e.id]}),:include_blank=>'Please Seletc LeaveType'%>
 		</td>
 	</tr>
 	<tr>
 		<td>From Date</td>
 		<td><%=text_field_tag :datepicker,@leave_availd.first.from_date%></td>
 	</tr>
 	<tr>
        <td>To Date</td>
        <td><%=text_field_tag :datepicker1,@leave_availd.first.to_date %></td>
    </tr>
         <td>Reasion</td>
         <td><%=text_field_tag :reasion,@leave_availd.first.reasion%></td>
    <tr> 
    </tr>
 </table>
 <%=submit_tag 'Update',:onclick=>'return validation();'%>
 <% end %>
 <script>
         $(document).ready(function () {
         $('input[id$=datepicker]').datepicker({ dateFormat: 'yy-mm-dd'}).val();
         $('input[id$=datepicker1]').datepicker({ dateFormat: 'yy-mm-dd'}).val();
    });
         function validation() {
            var leave = document.getElementById('hobbies').value;
            var from = document.getElementById('datepicker').value;
            var to = document.getElementById('datepicker1').value;
            var reasion = document.getElementById('reasion').value;
            var a =new Date(Date.parse(from))
            var b = new Date(Date.parse(to))
            if (leave=="") {
                alert('Please Select LeaveType')
                return false;
            }    
            if(from=="") {
             alert('Please select From Date')
             return false;
            } 
            if(to=="") {
             alert("Please select To Date")
             return false;
            }
            if(+b < +a){
             alert('From Date should less than To Date')
             return false;
            }
            if (reasion==""){
              alert('Please give reasion')
              return false;
            }

            return true;
         }
 </script>

app/views/leave_availd_details/index.html.erb
<div class="container">
  <h2>Leave Request Detail</h2>           
  <table class="table table-striped">
    <thead>
      <tr>
        <th>User Name</th>
        <th>Leave Type</th>
        <th>Total Days</th>
        <th>From Date</th>
        <th>TO Date</th>
        <th>Reasion</th>
        <th>Status</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
    <%if @leave_availd%>
    <%@leave_availd.each do |l|%>
      <tr>
        
        <td><%=l.user.name%></td>
        <td><%=l.leave_type.name%></td>
        <td><%=l.no_of_days%></td>
        <td><%=l.from_date%></td>
        <td><%=l.to_date%></td>
        <td><%=l.reasion%></td>
        <td><%=l.status%></td>
        <td><%=link_to 'Approve',approval_leave_leave_availd_detail_path(l.id)%></td>
        <td><%=link_to 'Reject',reject_leave_leave_availd_detail_path(l.id)%></td>
         
      </tr>
      <%end%><%end%>
    </tbody>
  </table>

app/views/leave_availd_details/new.html.erb
<center><h4>Apply Leaves</h4></center>
<br />
<%= form_tag(:controller => "leave_availd_details", :action => "create")%>
 <table>
 	<tr>
 		<td style="width: 140px">Leave Type</td>
 		<td><%#=collection_select(:post, :leave_type_id, LeaveType.all, :id,:name,:prompt=>true)%>
 			<%=select_tag "leave_type_id", options_from_collection_for_select(@leave_type, 'id', 'name'),:include_blank=>'Please select LeaveType'%>
 		</td>
 	</tr>
 	<tr>
 		<td>From Date</td>
 		<td><%=text_field_tag :datepicker %></td>
 	</tr>
 	<tr>
        <td>To Date</td>
        <td><%=text_field_tag :datepicker1 %></td>
    </tr>
         <td>Reasion</td>
         <td><%=text_field_tag :reasion%></td>
    <tr> 
    </tr>
 </table>
 <%=submit_tag 'Create',:onclick=>"return validation();"%>
    <script>
         $(document).ready(function () {
         $('input[id$=datepicker]').datepicker({ dateFormat: 'yy-mm-dd'}).val();
         $('input[id$=datepicker1]').datepicker({ dateFormat: 'yy-mm-dd'}).val();
    });
     function validation(){
        var leave = document.getElementById('leave_type_id').value;
     	var from = document.getElementById('datepicker').value;
     	var to = document.getElementById('datepicker1').value;
     	var reasion = document.getElementById('reasion').value;
     	var a =new Date(Date.parse(from))
     	var b = new Date(Date.parse(to))  
          if(leave==""){
            alert('Please select LeaveType')
            return false;
          }	
          if(from=="") {
             alert('Please select From Date')
             return false;
           } 
           if(to=="") {
           	 alert("Please select To Date")
     	  	 return false;
     	   }
     	    if(+b < +a){
             alert('From Date should less than To Date')
             return false;
     	   }
     	   if (reasion==""){
     	   	  alert('Please give reasion')
     	   	  return false;
     	   }

     	   	return true;
     	   
     }

    </script>
    